name: OnPushNewVersion

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Checkout skyview
        uses: actions/checkout@v2
        with:
          repository: impleotv/skyview
          token: ${{ secrets.TOKEN }}
          path: ./skyview
       
      - name: Copy CHANGELOG.md from skyview and create install
        run: |        
          cp ./skyview/CHANGELOG.md ./CHANGELOG.md 
          cp ./skyview/docker-compose.yml ./docker-compose.yml
          mkdir ./skyview/installDist
          cd ./skyview/install
          tar -czvf ../installDist/skyview-install.tar.gz . 
          sleep 5               
          cd ../../
          cp ./skyview/installDist/skyview-install.tar.gz  ./                 
          
      - name: List files in the repository and clean up
        run: |
          tree -L 2 ${{ github.workspace }}
          rm -rf ./skyview

      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}

      - name: Setup NodeJs 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}       
      - name: Generate README file
        run: node index.js ${{env.RELEASE_VERSION }}

      # - name: Clean up
      #   run: |
      #     rm -rf ./components

      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release    
        uses: ncipollo/release-action@v1
        with:
          artifacts: "skyview-install.tar.gz, skyview-install-wsl.tar.gz, CHANGELOG.md"       
          token: ${{ secrets.GITHUB_TOKEN }}
        
